### ISSUE TITLE
怎么配置成中文？改zh-Hans 不生效

### ISSUE THREAD

**Issue by zackzeng00** [Haojen/Claudia-theme-blog#8]

**Comment by Haojen** [comment]
@zackzeng00  Sorry for about that, I'm try to fix this problem ,they will be come soon

**Comment by Haojen** [comment]
@zackzeng00 I'm fixed it,  please `git pull` fetch the theme git repo and change `language: zh-Hans` -> `language: zh-CN` , Here is [My blog config ](https://github.com/Haojen/Claudia-theme-blog/blob/master/_config.yml)

**Comment by zackzeng00** [comment]
Let me try
